# Generated by Django 3.2.8 on 2021-12-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
