# Generated by Django 3.2.8 on 2021-12-19 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-paid_at']},
        ),
    ]
