# Generated by Django 3.2.8 on 2021-12-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['paid_at']},
        ),
    ]
